// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsk_ws7atg1O3A1WM0ZHpNNr31thV-coU',
    appId: '1:524228019734:web:b1c90fc530ab92083c9737',
    messagingSenderId: '524228019734',
    projectId: 'flutter-pushnotification-58a44',
    authDomain: 'flutter-pushnotification-58a44.firebaseapp.com',
    storageBucket: 'flutter-pushnotification-58a44.appspot.com',
    measurementId: 'G-YLR9ZBZGHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtwHSgStuwM_GySkDcyI4YlG3wSsog6OA',
    appId: '1:524228019734:android:ff2aa521b983ea783c9737',
    messagingSenderId: '524228019734',
    projectId: 'flutter-pushnotification-58a44',
    storageBucket: 'flutter-pushnotification-58a44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfbX4yhOscafoenGivZOyaGUrNk9jCakE',
    appId: '1:524228019734:ios:1cc7d4fe564dce7d3c9737',
    messagingSenderId: '524228019734',
    projectId: 'flutter-pushnotification-58a44',
    storageBucket: 'flutter-pushnotification-58a44.appspot.com',
    iosBundleId: 'com.example.fcmPushnotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfbX4yhOscafoenGivZOyaGUrNk9jCakE',
    appId: '1:524228019734:ios:1cc7d4fe564dce7d3c9737',
    messagingSenderId: '524228019734',
    projectId: 'flutter-pushnotification-58a44',
    storageBucket: 'flutter-pushnotification-58a44.appspot.com',
    iosBundleId: 'com.example.fcmPushnotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsk_ws7atg1O3A1WM0ZHpNNr31thV-coU',
    appId: '1:524228019734:web:4c8ad057e085c1f13c9737',
    messagingSenderId: '524228019734',
    projectId: 'flutter-pushnotification-58a44',
    authDomain: 'flutter-pushnotification-58a44.firebaseapp.com',
    storageBucket: 'flutter-pushnotification-58a44.appspot.com',
    measurementId: 'G-GB9DQ1G4K0',
  );
}
